import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class SendgridService {
    private sgMail = require('@sendgrid/mail')

    constructor(private config: ConfigService) {
        this.sgMail.setApiKey(this.config.get('SENDGRID_API'));
    }

    async sendEmail(...emails: Array<string>) {
        for (const email of emails) {
            try {
                console.log(email);
                await this.sgMail.send({
                    from: "anthesis@ukr.net",
                    to: "4nthesis@gmail.com",
                    subject: "Viso Test Assignment Email",
                    text: "We got 10 more writes in the Google Sheet!\n\nThis is a autogenerated message made for Viso test assignment, i apologize for possible spam",
                });
                console.log(`Email sent to - ${email}`);
            } catch (err: any) {
                console.error(err.message);
            }
        }
    }
}
