import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Client } from '@sendgrid/client';
import sgMail = require('@sendgrid/mail')

@Injectable()
export class SendgridService {
    constructor(private config: ConfigService) {
        sgMail.setClient(new Client());
        sgMail.setApiKey(this.config.get('SENDGRID_API'));
    }

    sendEmail(...emails: Array<string>) {
        emails.forEach(async (email) => {
            try {
                await sgMail.send({
                    from: "anthesis@ukr.net",
                    to: email,
                    subject: "Viso Test Assignment Email",
                    text: "We got 10 more writes in the Google Sheet!\n\nThis is a autogenerated message made for Viso test assignment, i apologize for possible spam",
                });
                console.log(`Email sent to - ${email}`);
            } catch (err: any) {
                console.error(err.message);
            }
        });
    }
}
